from app import db

from models import db, connect_db, User, Post, Dm, Follows, Likes, Story, Save, Comment, CommentLikes
from datetime import datetime

db.drop_all()
db.create_all()

user1m = User.signup(username = 'johndoe', password= 'password', email = 'johndoe@gmail.com', image= "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1600")
user2m = User.signup(username = 'markdoe', password ='password', email= 'markdoe@gmail.com', image= "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=1600")
user1f = User.signup(username = 'janedoe', password = 'password', email = 'janedoe@gmail.com', image= "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&w=1600")
user2f = User.signup(username = 'lisadoe', password = 'password', email = 'lisadoe@gmail.com', image= "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600")

db.session.add(user1m)
db.session.add(user2m)
db.session.add(user1f)
db.session.add(user2f)
db.session.commit()

first_post = Post(user_id = user1m.id, media='https://www.youtube.com/embed/lNdOcFaVkL4', caption ='After Waking From Two-Year Coma, Woman Names Brother As Her Attacker')
second_post = Post(user_id = user1m.id, media='https://www.youtube.com/embed/a1Ld8ONWCE8', caption ='Bannon Threatens To Go Medieval In Contempt Trial, Judge Clearly Doesnt Care')
third_post = Post(user_id = user1m.id, media='https://www.youtube.com/embed/iExzgxmE9OE', caption ='Forest fires rage across Europe as heatwave tightens its grip')
fourth_post = Post(user_id = user1m.id, media='https://www.youtube.com/embed/wmP57dj7L9A', caption ='Soaring rents price out some Canadians')
fifth_post = Post(user_id = user1m.id, media='https://www.youtube.com/embed/d_wRcj0MCro', caption ='Wildfires forcing evacuations in northern Manitoba and B.C.')
sixth_post = Post(user_id = user1f.id, media='https://www.youtube.com/embed/C-qsnDLdq68', caption ='Whats behind the shortage of family doctors in Canada?')
seventh_post = Post(user_id = user1f.id, media='https://www.youtube.com/embed/ugM3i9RH_pM', caption ='Wildfires prompt evacuation of First Nation in northern Manitoba')
eighth_post = Post(user_id = user1f.id, media='https://www.youtube.com/embed/oepZJW6A4tc', caption ='Why this Ottawa woman is learning Indigenous sign language to connect with her culture')
ninth_post = Post(user_id = user2m.id, media='https://www.youtube.com/embed/g-X67dm6lAY', caption ='Fallout continues over Ottawas release of turbines')
tenth_post = Post(user_id = user2f.id, media='https://www.youtube.com/embed/yV78etXN96U', caption ='Partner of N.S. mass shooter testifies in person for the first time')
older_post = Post(user_id = user1f.id, media ='https://www.youtube.com/embed/Dh5C-F5hSXQ', caption = 'This is more than a week old', timestamp = '20220728 12:45:09 PM' )
older_post2 = Post(user_id = user1m.id, media ='https://www.youtube.com/embed/Dh5C-F5hSXQ', caption = 'This is also more than a week old')
picture_post1 = Post(user_id = user1m.id, media='https://images.unsplash.com/photo-1654460183597-cdb42454716f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', caption ='Lorem ipsum dolor sit amet. Ut cumque minima et sunt incidunt et libero quia. Ut nemo sint qui mollitia soluta sed Quis aliquid aut itaque quasi est cumque reiciendis et molestiae mollitia quo exercitationem expedita. Est nemo veritatis a itaque sunt ut enim omnis eum debitis minima nam earum dolor et magnam eius. 33 placeat enim et rerum assumenda quo mollitia earum aut corrupti architecto.Eum cumque consectetur aut internos minima est rerum alias. Et illum consequatur et quod numquam ut ipsa eius et quia harum rem nihil mollitia est obcaecati impedit quo itaque nesciunt! A quos voluptas qui similique ullam id error dolores qui culpa deserunt rem voluptatem sapiente et voluptatem fugit. 33 magnam rerum est enim illo et dicta enim 33 rerum tenetur.')
picture_post2 = Post(user_id = user2m.id, media = 'https://images.unsplash.com/photo-1658893769271-c2461cab05b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', caption = 'Some great raspberries!')
picture_post3 = Post(user_id = user1f.id, media = 'https://images.unsplash.com/photo-1658947051795-1bbc7e132847?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', caption = 'Some pottery!')
picture_post4 = Post(user_id = user2f.id, media = 'https://images.unsplash.com/photo-1658959601004-89911c69089f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', caption = 'A picture of my dog!')


db.session.add(first_post)
db.session.add(second_post)
db.session.add(third_post)
db.session.add(fourth_post)
db.session.add(fifth_post)
db.session.add(sixth_post)
db.session.add(seventh_post)
db.session.add(eighth_post)
db.session.add(ninth_post)
db.session.add(tenth_post)
db.session.add(older_post)
db.session.add(older_post2)
db.session.add(picture_post1)
db.session.add(picture_post2)
db.session.add(picture_post3)
db.session.add(picture_post4)
db.session.commit()

comment1 = Comment(commentor = 'johndoe', post_id = first_post.id, text = 'very informative', timestamp = datetime.utcnow())
comment2 = Comment(commentor = 'johndoe', post_id = second_post.id, text = 'awesome', timestamp = datetime.utcnow())
comment3 = Comment(commentor = 'johndoe', post_id = third_post.id, text = 'wow', timestamp = datetime.utcnow())
comment4 = Comment(commentor = 'janedoe', post_id = first_post.id, text = 'oh my', timestamp = datetime.utcnow())
comment5 = Comment(commentor = 'janedoe', post_id = second_post.id, text = 'interesting article', timestamp = datetime.utcnow())
comment6 = Comment(commentor = 'janedoe', post_id = third_post.id, text = 'great', timestamp = datetime.utcnow())

db.session.add(comment1)
db.session.add(comment2)
db.session.add(comment3)
db.session.add(comment4)
db.session.add(comment5)
db.session.add(comment6)
db.session.commit()

comment_like_1 = CommentLikes(liked_comment_id = comment1.id, liking_user = 'markdoe')
comment_like_2 = CommentLikes(liked_comment_id = comment2.id, liking_user = 'markdoe')
db.session.add(comment_like_1)
db.session.add(comment_like_2)
db.session.commit()

postlike1 = Likes(liked_post_id=first_post.id, user_liking_id = user1m.id)
postlike2 = Likes(liked_post_id=first_post.id, user_liking_id = user2m.id)
postlike3 = Likes(liked_post_id=first_post.id, user_liking_id = user1f.id)
postlike4 = Likes(liked_post_id=first_post.id, user_liking_id = user2f.id)
db.session.add(postlike1)
db.session.add(postlike2)
db.session.add(postlike3)
db.session.add(postlike4)
db.session.commit()

follows1 = Follows(user_following_id = user1m.id, followed_user_id = user2m.id)
follows2 = Follows(user_following_id = user1f.id, followed_user_id = user2m.id)
follows3 = Follows(user_following_id = user2f.id, followed_user_id = user2m.id)
follows4 = Follows(user_following_id = user2m.id, followed_user_id = user1m.id)
follows5 = Follows(user_following_id = user2m.id, followed_user_id = user1f.id)
follows6 = Follows(user_following_id = user2m.id, followed_user_id = user2f.id)
db.session.add(follows1)
db.session.add(follows2)
db.session.add(follows3)
db.session.add(follows4)
db.session.add(follows5)
db.session.add(follows6)
db.session.commit()
